package com.joaaoferreiira.celebridades.util

import com.joaaoferreiira.celebridades.database.entity.FraseEntity

object FrasesUtil {

    fun getFrases(): List<FraseEntity> {
        var idContador = 0
        var celebId = 0

        return listOf(
            //Justin Bieber
            FraseEntity(++idContador, ++celebId, "Minha mensagem é que você pode fazer qualquer coisa se você colocar isso na cabeça. Eu cresci abaixo da linha da pobreza, eu não tive tanto quanto as outras pessoas. Acho que isso me fez mais forte como uma pessoa, foi o que construiu meu caráter. Agora eu estou em um grau de 4.0, e quero ir para a faculdade e me tornar uma pessoa melhor."),
            FraseEntity(++idContador, celebId, "Nunca pensei que seria fácil porque ambos estamos tão distantes agora, as paredes estão se fechando sobre nós e estamos nos perguntando como ninguém tem uma resposta concreta. Mas estamos apenas andando no escuro, e você pode ver a expressão no meu rosto, simplesmente me detona"),
            FraseEntity(++idContador, celebId, "Então depende de você e também depende de mim, mas nos encontraremos no meio, no nosso caminho de volta com os pés no chão."),
            FraseEntity(++idContador, celebId, "Eu esperaria por você para sempre, todos os dias. Seu mundo é meu mundo, yeah."),
            FraseEntity(++idContador, celebId, "Nunca diga nunca!"),
            FraseEntity(++idContador, celebId, "Eu nasci para ser alguém,eu vou iluminar o céu, eu nasci para dignificar, eu posso sentir isso, eu posso acreditar,estou aqui para ficar. Sinta, Acredite, Sonhe, Seja!!!"),
            FraseEntity(++idContador, celebId, "Agora Romeu e Julieta nunca se sentiriam do jeito que nos sentimos."),
            FraseEntity(++idContador, celebId, "Não peço que comecem a gostar de mim, eu só peço um pouco de respeito, que nada foi fácil até agora."),
            FraseEntity(++idContador, celebId, "Bem-aventurados todos nós devemos ser capazes de desempenhar um pequeno papel em trazer alegria para a vida das pessoas."),
            FraseEntity(++idContador, celebId, "Eu quero ter meus fãs crescendo comigo e não apenas ser um artista teen. Quero ser um artista quando adulto. Justin Timberlake e Usher, por exemplo. Os dois começaram bem novos e olha como eles fazem as coisas agora."),
            FraseEntity(++idContador, celebId, "Quando eu penso sobre os meus fãs, eu imagino como a Beyoncé faria."),
            FraseEntity(++idContador, celebId, "Ainda gosto de vocês, mas convenhamos: estou com cara de louco. Porém, se você não ri de você mesmo é porque não está se divertindo."),
            FraseEntity(++idContador, celebId, "É muito louco eu, que vim de uma pequena cidade do Canadá, agora poder viajar o mundo todo e fazer o que amo. Eu postava vídeos na internet só para me divertir. Nunca pensei que isso seria possível, então nunca havia sonhado realmente com tudo isso."),
            FraseEntity(++idContador, celebId, "As pessoas escrevem pra mim dizendo: 'Eu estou desistindo, você não está falando comigo.' e eu escrevo (no twitter) uma simples mensagem tipo: 'Nunca desista!' e, isso acaba mudando a vida delas."),
            FraseEntity(++idContador, celebId, "Me sinto o Kurt Cobain da minha geração, mas as pessoas não me compreendem."),
            FraseEntity(++idContador, celebId, "A canção mais pessoal que eu escrevi foi 'Down To Earth', porque é sobre como os meus pais se separaram quando eu era muito novo. Fala da vida cotidiana e de como há regras."),
            FraseEntity(++idContador, celebId, "Eu perco meu apetite sabendo que crianças passam fome à noite. Eu sou um pecador por que meu jantar ainda está no meu prato?"),
            FraseEntity(++idContador, celebId, "Eu nunca vou dizer nunca. Eu lutarei!"),
            FraseEntity(++idContador, celebId, "Eu nunca pensei que poderia sentir esse poder. Eu nunca pensei que pudesse sentir essa liberdade. Eu sou forte o suficiente para subir a torre mais alta e eu sou rápido o suficiente para correr sobre o mar."),
            FraseEntity(++idContador, celebId, "Eu vou lutar para sempre, fazer o certo. Sempre que você me derrubar eu não vou ficar no chão, vou levantar!"),

            //Beyonce
            FraseEntity(++idContador, ++celebId, "Eu te queria tanto, mas não sinto mais isso. Porque, honestamente, você acabou por ser a melhor coisa que nunca tive"),
            FraseEntity(++idContador, celebId, "Eu sempre vou ser sempre a melhor coisa que você nunca teve"),
            FraseEntity(++idContador, celebId, "Você não merece as minhas lágrimas"),
            FraseEntity(++idContador, celebId, "Graças a Deus encontrei o lado bom em dizer adeus"),
            FraseEntity(++idContador, celebId, "Você acorda, perfeita. Bota a cara no sol, perfeita. Anda por aí, perfeita. Se exibe, perfeita"),
            FraseEntity(++idContador, celebId, "Acordei assim! Somos perfeitas, garotas, contem a eles"),
            FraseEntity(++idContador, celebId, "Eu sou perfeita"),
            FraseEntity(++idContador, celebId, "Eu posso sentir o Sol sempre que você está perto. Toda vez que você me toca eu me derreto toda"),
            FraseEntity(++idContador, celebId, "Amor, é você! Você é aquele que eu amo! Você é aquele que eu preciso! Você é o único que eu vejo"),
            FraseEntity(++idContador, celebId, "Você é aquele que dá tudo de si, você é aquele que eu posso sempre chamar. Quando preciso de você, você faz tudo parar"),
            FraseEntity(++idContador, celebId, "Seus lábios tem gosto de uma noite de champanhe"),
            FraseEntity(++idContador, celebId, "Eu arranjo outro como você amanhã. Então não ouse pensar por um segundo sequer que você é insubstituível"),
            FraseEntity(++idContador, celebId, "Está falando sobre como eu nunca vou encontrar um homem igual a você. Você me confundiu com outra pessoa"),
            FraseEntity(++idContador, celebId, "Então, já que eu não sou o seu tudo, que tal eu ser o seu nada?"),
            FraseEntity(++idContador, celebId, "Querido, eu não vou derramar uma lágrima por você, não vou perder uma noite de sono. Porque a mais pura verdade é que substituir você é muito fácil"),
            FraseEntity(++idContador, celebId, "Porque eu sei que não entendo como o seu amor consegue fazer o que ninguém mais consegue"),
            FraseEntity(++idContador, celebId, "Seu amor está me fazendo parecer tão louca agora"),
            FraseEntity(++idContador, celebId, "Em todos os lugares que estou olhando agora eu estou cercada pelo o seu abraço"),
            FraseEntity(++idContador, celebId, "Você é tudo que eu preciso e mais"),
            FraseEntity(++idContador, celebId, "Você é o único que eu quero. Acho que estou viciada na sua luz"),

            //Daniel Radcliffe
            FraseEntity(++idContador, ++celebId, "A vítima de bullying não tem como escapar porque agora o acesso a eles ficou mais fácil. Quando você sofria agressão na escola dava pra fugir no final da aula, mas agora você pode ser caçado por celular, Facebook, Twitter. é assustador"),
            FraseEntity(++idContador, celebId, "Ficarei triste em encerrar a série, mas terei uma grande sensação de dever cumprido quando o filme acabar, porque terá sido a mais longa filmagem que eu provavelmente farei em toda minha carreira"),
            FraseEntity(++idContador, celebId, "Sim, quer dizer, eu coloco numa cesta e ela, de repente, volta limpa. Minhas tarefas em casa são manter meu quarto minimamente arrumado e limpo, num nível aceitável de higiene."),
            FraseEntity(++idContador, celebId, "Os homossexuais devem ter igualdade de direito em todos os lugares. Se você crescer como um jovem gay, sabendo que não tem as mesmas oportunidades que todo mundo, você se sente vítima e prejudica a si mesmo"),
            FraseEntity(++idContador, celebId, "Muitas vezes as pessoas gritam 'Hey Frodo!', porque pensam que sou Elijah (Wood). Eu encaro isso como um elogio, já que ele é um cara muito bonito! Eu admito que quando alguém se confunde e vem me pedir autógrafo, eu dou e assino: 'Com amor, Elijah Wood'. Seria muito triste para mim se eu falasse a verdade e a pessoa desistisse da assinatura“\n"),
            FraseEntity(++idContador, celebId, "O ruim de ficar com uma delas é que você acaba encontrando e tendo que conversar depois. Já aconteceu, mas, tirando algumas vezes, eu estava bêbado“\n"),
            FraseEntity(++idContador, celebId, "Este ano, eu tenho parado para admirar o talento de Ryan Gosling. Acho ele fantástico e parece ser muito legal. Ele parece inteligente. Se eu fosse gay, eu escolheria um homem inteligente como ele"),
            FraseEntity(++idContador, celebId, "Fiquei dependente (da bebida) para desfrutar das coisas. Houve alguns anos nos quais estava apaixonado pela ideia de viver uma vida de pessoa famosa."),
            FraseEntity(++idContador, celebId, "Aquilo (Harry Potter) foi a minha infância, a qual eu disse adeus."),
            FraseEntity(++idContador, celebId, "Estou muito bonito lá de qualquer maneira cara! Tem uma quantidade enorme … Não faço muita manutenção por lá, cara. Quero dizer, só um pouquinho, por cortesia"),
            FraseEntity(++idContador, celebId, "Eu não gosto de garotas com nada lá em baixo também … Esse tipo de mulher me assusta. Você tem que ter alguma coisa, caso contrário, é assustador"),
            FraseEntity(++idContador, celebId, "Eu não acho que o Oscar goste de filmes comerciais, ou filmes de crianças, a menos que sejam dirigidos pelo Martin Scorsese"),
            FraseEntity(++idContador, celebId, "Eu conheço o trabalho de Lady Gaga. Eu a acho brilhante. Ela tem uma linda voz"),
            FraseEntity(++idContador, celebId, "Muito, muito emocionante. Me lembro de ter chorado feito criança"),
            FraseEntity(++idContador, celebId, "Só fui ouvir Justin Bieber pela primeira vez há duas semanas. Ao ouvir a música, pensei que se tratava de uma menina. Nunca o tinha ouvido"),
            FraseEntity(++idContador, celebId, "Tenho muito orgulho de ser judeu. Isso significa que tenho uma boa ética de trabalho, e você tem humor judaico e pode contar piadas judaicas."),
            FraseEntity(++idContador, celebId, "Certa vez, um amigo me chamou (Harry) por acidente. Se houver outra pessoa na sala chamada Harry e alguém gritar seu nome, eu respondo um pouco, o que é embaraçoso. Mas ninguém nunca disse isso nas jogadas da paixão. Esse seria o fim dessa sessão. Vá agora!"),
            FraseEntity(++idContador, celebId, "É bom voltar a filmar. Coloquei meus óculos e me tornei Harry novamente."),
            FraseEntity(++idContador, celebId, "Eu e Harry (Potter) não somos muito bons com mulheres. Eu melhorei agora. Mas acho que qualquer homem que diz que nunca teve um momento estranho com uma garota é mentiroso. Ele é um mentiroso ou é ilusório."),
            FraseEntity(++idContador, celebId, "Eu gostaria de ser ator, mas há muitas outras coisas que também me interessam, como música, escrita e esportes. Eu quero manter minhas opções em aberto."),

            //Quarta celebridade
            FraseEntity(++idContador, ++celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),

            //Quinta celebridade
            FraseEntity(++idContador, ++celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),

            //Sexta celebridade
            FraseEntity(++idContador, ++celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),

            //Setima celebridade
            FraseEntity(++idContador, ++celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),

            //Oitava celebridade
            FraseEntity(++idContador, ++celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),

            //Nona celebridade
            FraseEntity(++idContador, ++celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),

            //Decima celebridade
            FraseEntity(++idContador, ++celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),

            //11 celebridade
            FraseEntity(++idContador, ++celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),

            //12 celebridade
            FraseEntity(++idContador, ++celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),

            //13 celebridade
            FraseEntity(++idContador, ++celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),

            //Emma Watson
            FraseEntity(++idContador, ++celebId, "Não se sinta uma idiota se você não gostar do que todo mundo finge adorar."),
            FraseEntity(++idContador, celebId, "É uma jornada e a coisa triste é que você só aprende com a experiência, então não importa o quanto alguém te diga as coisas, você tem de ir lá e cometer seus próprios erros para aprender."),
            FraseEntity(++idContador, celebId, "Tem atrizes que não sabem coisas como lavar roupa ou pegar um ônibus. Não quero ser assim."),
            FraseEntity(++idContador, celebId, "Quanto mais discurso sobre feminismo, percebo que lutar pelos direitos das mulheres tem se tornado sinônimo de odiar homens. Isso tem de parar."),
            FraseEntity(++idContador, celebId, "Não tenho dentes perfeitos. Quero ser alguém que se sente bem no próprio corpo."),
            FraseEntity(++idContador, celebId, "Para mim, atrizes bem-sucedidas são as que se sentem confortáveis na própria pele e parecem humanas.\""),
            FraseEntity(++idContador, celebId, "O feminismo não está aqui para ditar o que você deve fazer. Estamos aqui para te dar chance de escolher. Se você quiser ser presidente, você pode. Se não, tudo lindo também. Depile as axilas, não depile, vista saldo em um dia e sapatos baixos no outro."),
            FraseEntity(++idContador, celebId, "Eu sou literalmente obcecada pela Lena Dunham. Ela é minha pessoa favorita no mundo todo."),
            FraseEntity(++idContador, celebId, "A maior parte dos garotos foi, tipo, 'Por que você cometeu esse erro?'. E eu: 'Honestamente, não dou a mínima para o que você pensa!' Nunca me senti tão confiante quanto quando estou com o cabelo curto."),
            FraseEntity(++idContador, celebId, "Se eles estavam tentando me calar, eles conseguiram o oposto."),
            FraseEntity(++idContador, celebId, "Cozinhar me ajuda a relaxar e acho que as pessoas próximas de nós apreciam uma comidinha feita em casa."),
            FraseEntity(++idContador, celebId, "Olha. Eu só quero saber exatamente como serão os próximos dez anos da minha vida, ok? E ter isso organizado em um calendário separado por cores. Será que isso é pedir muito?!"),
            FraseEntity(++idContador, celebId, "Todo mundo já me viu com meus horríveis cortes de cabelo e meus dentes medonhos, e todas as coisas pavorosas que eu vesti e as coisas estúpidas que disse. Quero dizer, teve um vestido que usei na estreia do último Harry Potter. Eu parecia um merengue"),
            FraseEntity(++idContador, celebId, "Meus pais não conseguem desencanar. Na Inglaterra nós nos formamos em três anos e meu pai está tipo, 'Quando você vai se formar, porque você está demorando décadas?'"),
            FraseEntity(++idContador, celebId, "Eu neguei enquanto pude. Até os 18 anos, eu pegava ônibus em Oxford. Até que o fato de que eu estava no ônibus se espalhava de ponta a ponta. Ignorar a fama era minha rebelião."),
            FraseEntity(++idContador, celebId, "Acho que ganhei o direito de estragar tudo algumas vezes. Não quero que o medo de fracassar me impeça de fazer o que eu realmente é importante para mim."),
            FraseEntity(++idContador, celebId, "Eu pergunto para as minhas amigas, 'por que ele não me ligou?'. Elas dizem, 'provavelmente porque ele ficou intimidado'. Deve ser o circo que vive em torno de mim. Eu acho difícil acreditar que sou intimidadora."),
            FraseEntity(++idContador, celebId, "Tanto os homens como as mulheres devem se sentir no direito de serem fortes. Já é hora de vermos os gêneros como um conjunto, e não como um jogo de polos opostos. Devemos parar de nos desafiar uns aos outros."),
            FraseEntity(++idContador, celebId, "As mulheres jovens são levadas a crer que precisam ser algum tipo de princesa, delicada e frágil, e isso é uma estupidez."),
            FraseEntity(++idContador, celebId, "Se for para ser princesa, eu quero ser uma princesa guerreira, definitivamente."),

            //Chico Buarque
            FraseEntity(++idContador, ++celebId, "As pessoas têm medo das mudanças. Eu tenho medo que as coisas nunca mudem."),
            FraseEntity(++idContador, celebId, "Quero inventar o meu próprio pecado. Quero morrer do meu próprio veneno."),
            FraseEntity(++idContador, celebId, "Apesar de você, amanhã há de ser outro dia"),
            FraseEntity(++idContador, celebId, "Quem sabe um dia, por descuido ou poesia, você goste de ficar?"),
            FraseEntity(++idContador, celebId, "O nosso amor é tão bom. O horário é que nunca combina."),
            FraseEntity(++idContador, celebId, "Para sempre é sempre por um triz."),
            FraseEntity(++idContador, celebId, "Eu canto a dor que eu não soube chorar."),
            FraseEntity(++idContador, celebId, "Está provado, quem espera nunca alcança."),
            FraseEntity(++idContador, celebId, "Talvez nem me queira bem; Porém faz um bem que ninguém me faz."),
            FraseEntity(++idContador, celebId, "Não se afobe não que nada é pra já!"),
            FraseEntity(++idContador, celebId, "Eu semeio vento na minha cidade, vou pra rua e bebo a tempestade."),
            FraseEntity(++idContador, celebId, "Quando chegar o momento, esse meu sofrimento vou cobrar com juros, juro."),
            FraseEntity(++idContador, celebId, "...e pela minha lei, a gente era obrigada a ser feliz."),
            FraseEntity(++idContador, celebId, "Não há mais porta, mas também não tenho mais vontade de entrar."),
            FraseEntity(++idContador, celebId, "Eu vou rasgar meu coração pra costurar o teu."),
            FraseEntity(++idContador, celebId, "A saudade é o revés de um parto."),
            FraseEntity(++idContador, celebId, "E qualquer desatenção, faça não! Pode ser a gota d'água."),
            FraseEntity(++idContador, celebId, "Não me leve a mal; Me leve à toa pela última vez"),
            FraseEntity(++idContador, celebId, "E nada como um tempo após um contratempo pro meu coração."),
            FraseEntity(++idContador, celebId, "Aquela esperança de tudo se ajeitar… Pode esquecer."),

            //Lulu Santos
            FraseEntity(++idContador, ++celebId, "Hoje o tempo voa amor, escorre pelas mãos mesmo sem se sentir. Não há tempo que volte amor, vamos viver tudo que há pra viver, vamos nos permitir."),
            FraseEntity(++idContador, celebId, "E não há lógica que faça desandar o que o acaso decidir."),
            FraseEntity(++idContador, celebId, "Ela me encontrou, eu tava por aí, num estado emocional tão ruim, me sentindo muito mal, sozinho, perdido, andando de bar em bar…"),
            FraseEntity(++idContador, celebId, "Eu gosto tanto de você que até prefiro esconder. Deixo assim ficar subentendido."),
            FraseEntity(++idContador, celebId, "Não vou dizer que foi ruim, também não foi tão bom assim… Não imagine que te quero mal, apenas não te quero mais."),
            FraseEntity(++idContador, celebId, "Nada do que foi será do jeito que já foi um dia…"),
            FraseEntity(++idContador, celebId, "Ela demonstrou tanto prazer de estar em minha companhia, eu experimentei uma sensação que até então não conhecia…"),
            FraseEntity(++idContador, celebId, "Quando um certo alguém desperta o sentimento é melhor não resistir, e se entregar."),
            FraseEntity(++idContador, celebId, "Vamos viver tudo o que há pra viver, vamos nos permitir."),
            FraseEntity(++idContador, celebId, "Tudo que se vê não é igual ao que a gente viu há um segundo, tudo muda o tempo todo no mundo."),
            FraseEntity(++idContador, celebId, "A vida é mesmo assim. Dia e noite, não e sim"),
            FraseEntity(++idContador, celebId, "A vida passa lentamente e a gente vai tão de repente."),
            FraseEntity(++idContador, celebId, "Mas o teu amor me cura de uma loucura qualquer"),
            FraseEntity(++idContador, celebId, "Nada do que foi será de novo do jeito que já foi um dia, tudo muda o tempo todo!"),
            FraseEntity(++idContador, celebId, "Vamos viver tudo o que há pra viver, vamos nos permitir."),
            FraseEntity(++idContador, celebId, "Tudo o que eu sonhei está a minha frente… Está em nossas mãos, é a nossa vida. Cada escolha sempre determina o que vem em seguida."),
            FraseEntity(++idContador, celebId, "Só falta eu te querer, te ganhar e te perder."),
            FraseEntity(++idContador, celebId, "Eu te amo calado, como quem ouve uma sinfonia. De silêncios e de luz."),
            FraseEntity(++idContador, celebId, "A beleza é mesmo tão fugaz."),
            FraseEntity(++idContador, celebId, "Não imagine que te quero mal, apenas não te quero mais."),

            //Marilia Mendonça
            FraseEntity(++idContador, ++celebId, "Se até o tempo passa, imagina o seu amor."),
            FraseEntity(++idContador, celebId, "Preocupa não, pra um bom entendedor, meia ausência basta!"),
            FraseEntity(++idContador, celebId, "Sei bem o que te faz bem."),
            FraseEntity(++idContador, celebId, "E o preço que eu pago é nunca ser amada de verdade."),
            FraseEntity(++idContador, celebId, "O meu coração que não muda de assunto… Toda hora ele tem que lembrar."),
            FraseEntity(++idContador, celebId, "Você não mereceu nem um pouco do amor que eu te dei."),
            FraseEntity(++idContador, celebId, "E quando se der conta, já passou. Quando olhar pra trás, já fui embora."),
            FraseEntity(++idContador, celebId, "Estou deixando o nosso ninho… Decidi voar sozinha."),
            FraseEntity(++idContador, celebId, "Vou em busca de outro amor. Não tem mais doce a nossa flor."),
            FraseEntity(++idContador, celebId, "Não perdi nada, acabei de me livrar."),
            FraseEntity(++idContador, celebId, "Só queria mais um pouco desse sentimento louco."),
            FraseEntity(++idContador, celebId, "Você me desmontou, sorriu de novo pra mim."),
            FraseEntity(++idContador, celebId, "Eu vivo do jeito que eu quero, não pedi opinião."),
            FraseEntity(++idContador, celebId, "Toda hora a gente briga sem explicação. Não tem amor, não tem respeito, não tem paixão."),
            FraseEntity(++idContador, celebId, "A culpa é sua por ter esse sorriso ou a culpa é minha por me apaixonar por ele?"),
            FraseEntity(++idContador, celebId, "Deixa, deixa mesmo de ser importante, vai deixando a gente pra outra hora. Vai tentar abrir a porta desse amor quando eu tiver jogado a chave fora."),
            FraseEntity(++idContador, celebId, "Sei que tá morrendo de saudade, vem buscar logo a sua metade."),
            FraseEntity(++idContador, celebId, "Foi você quem escolheu, foi você quem perdeu."),
            FraseEntity(++idContador, celebId, "Eu não sou obrigada a viver dando satisfação."),
            FraseEntity(++idContador, celebId, "E todo esse caminho eu sei de cor, se eu não me engano, agora vai me deixar só."),

            //Lady Gaga
            FraseEntity(++idContador, ++celebId, "Meu objetivo é me tornar a maior artista pop do planeta. E também quero uma exposição no Louvre."),
            FraseEntity(++idContador, celebId, "Bem, essa é a tua opinião, certo? E eu não estou a fim de perder o meu tempo para tentar mudá-la."),
            FraseEntity(++idContador, celebId, "Algumas mulheres escolhem seguir os homens, e outras escolhem seguir os seus sonhos. Se continuas indecisa em que caminho seguir, lembra-te que dessa forma a tua carreira nunca acordará e que um dia te irá dizer que já não te quer"),
            FraseEntity(++idContador, celebId, "Quando eu era morena, me chamavam de Amy Winehouse. Agora me chamam de Christina Aguilera e Gwen Stefani."),
            FraseEntity(++idContador, celebId, "Amar é estar em perigo, sempre. O amor faz você se arriscar, ser irracional. Mantém você vivo e também te destrói. […] Eu tenho medo que assim que eu achar um amor, não terei nada para escrever a respeito, mas talvez eu me apaixone por alguém que seja meu muso inspirador."),
            FraseEntity(++idContador, celebId, "Eu tinha um namorado que me dizia que eu nunca iria ser bem sucedida, nunca haveria de ser nomeada para um Grammy, nunca teria uma canção no top, e que tinha esperança que eu falhasse. E eu disse a ele: \"Um dia, quando já não estivermos juntos, não conseguirás pedir uma chávena de café em qualquer sítio sem que me estejas a ouvir ou a ver.\"."),
            FraseEntity(++idContador, celebId, "Quando fazes música ou escreves ou cries, é a tua missão ter uma mente explosivamente aberta, irresponsável, sem qualquer tabu com qualquer ideia que estejas a concretizar nessa altura."),
            FraseEntity(++idContador, celebId, "Eu costumava descer a rua como se fosse uma grande estrela. Eu quero que as pessoas alimentem as suas ilusões sobre o quão grandes se podem tornar - e depois lutarem tanto e tão fortemente por isso todos os dias, até que a mentira se torne verdade."),
            FraseEntity(++idContador, celebId, "Eu quero que todas as mulheres - e todos os homens - se deixem influenciar pela parte mais profunda e psicótica deles próprios. Essa parte que estão constantemente e desesperadamente a tentar esconder. Eu quero que essa parte se torne algo que eles venham a adorar."),
            FraseEntity(++idContador, celebId, "Calma! Um dia sua vida vai mudar, e tenho certeza que vai ser pra melhor."),
            FraseEntity(++idContador, celebId, "Achei que ia morrer, mas fui salva pelo espírito de minha tia: ele tomou conta do meu corpo e veio a visão de que eu tinha de parar."),
            FraseEntity(++idContador, celebId, "A confiança é como um espelho, podemos repará-lo se estiver partido, mas continuaremos sempre a ver a falha no reflexo daquela porcaria."),
            FraseEntity(++idContador, celebId, "Sou uma pessoa esquisita. Não gosto de ficar com celebridades e não me encaixo nesse mundo."),
            FraseEntity(++idContador, celebId, "Tudo o que mantém qualquer pessoa na defensiva, penso eu, é o medo. Por um minuto eu tive medo. Depois fui ao camarim e agredi o medo na cara."),
            FraseEntity(++idContador, celebId, "Fingir nem sempre é a melhor opção, mas é a necessária."),
            FraseEntity(++idContador, celebId, "Eles não me podem assustar, se eu os assustar primeiro."),
            FraseEntity(++idContador, celebId, "Eu não tinha ideia que andava gastando tanto com meus figurinos."),
            FraseEntity(++idContador, celebId, "Eu sou obsessivamente contra tudo o que é vulgar."),
            FraseEntity(++idContador, celebId, "Nunca permitam a ninguém que diminuam o vosso brilho, porque eles são cegos. Digam a eles que ponham os óculos de sol, porque foi desta maneira que nós nascemos!"),
            FraseEntity(++idContador, celebId, "Se não lutamos pelo que pensamos e se não lutamos por nossos direitos, muito em breve vamos ter tantos direitos quanto a carne de nossos ossos"),

            //Will Smith
            FraseEntity(++idContador, ++celebId, "Quando todos te abandonarem, os verdadeiros ficarão para te fazer sorrir."),
            FraseEntity(++idContador, celebId, "Você pode chorar, não há nenhuma vergonha nisso."),
            FraseEntity(++idContador, celebId, "Sou maduro o bastante para perdoar, mas não sou idiota o suficiente para confiar novamente..."),
            FraseEntity(++idContador, celebId, "Muitas pessoas gastam dinheiro que não tem, para comprar coisas que não precisam, para impressionar pessoas que não gostam."),
            FraseEntity(++idContador, celebId, "Se você não está fazendo da vida de alguém algo melhor, você está desperdiçando o seu tempo. Sua vida será melhor quando você fazer da vida de outras pessoas algo melhor."),
            FraseEntity(++idContador, celebId, "Ao longo da vida pessoas o deixarão furioso, o desrespeitarão e o tratarão mal. Deixe Deus lidar com as coisas que eles fazem, causar ódio em seu coração o consumirá também."),
            FraseEntity(++idContador, celebId, "A habilidade só é desenvolvida por horas e horas e horas de trabalho duro."),
            FraseEntity(++idContador, celebId, "Não deixe a falha atingir seu coração e não deixe o sucesso atingir sua cabeça."),
            FraseEntity(++idContador, celebId, "Algumas vezes você tem que esquecer o que foi, apreciar o que ficou e olhar além pelo que virá."),
            FraseEntity(++idContador, celebId, "O perigo existe de verdade mas o medo é fruto da nossa imaginação, somos nós que escrevemos nossa história, não deixe que o medo mude a sua e controle seu futuro!"),
            FraseEntity(++idContador, celebId, "A vida inteira as pessoas tentam te enlouquecer, te desrespeitar e te tratar mal. Deixe Deus cuidar disso, pois sentir ódio no coração também pode acabar te consumindo."),
            FraseEntity(++idContador, celebId, "Necessidade não é vergonha, necessidade é necessidade."),
            FraseEntity(++idContador, celebId, "As coisas que são mais valiosas para mim, eu não aprendi na escola."),
            FraseEntity(++idContador, celebId, "Sorrir é a melhor forma que você tem de enfrentar seus problemas, acalmar seus temores e esconder a dor."),
            FraseEntity(++idContador, celebId, "Se você não estiver melhorando a vida de alguém, está perdendo seu tempo."),
            FraseEntity(++idContador, celebId, "Ser realista é o caminho mais percorrido até a mediocridade."),
            FraseEntity(++idContador, celebId, "Não há motivos para ter um plano B, pois isso nos distrai do plano A."),
            FraseEntity(++idContador, celebId, "Eu acho que consigo criar qualquer coisa que quiser criar."),
            FraseEntity(++idContador, celebId, "Às vezes, é preciso esquecer o que passou, apreciar o que ainda resta e esperar o que virá depois"),
            FraseEntity(++idContador, celebId, "Amo viver, acho que é algo contagiante. É algo que não se pode fingir."),

            //Taylor Swift
            FraseEntity(++idContador, ++celebId, "Fiquei mais esperta, fiquei mais dura com o passar do tempo"),
            FraseEntity(++idContador, celebId, "Querido, eu me levantei dos mortos"),
            FraseEntity(++idContador, celebId, "A liberdade não é nada além de saudade sua."),
            FraseEntity(++idContador, celebId, "Você me deu todo o seu amor e tudo que eu te dei foi um adeus"),
            FraseEntity(++idContador, celebId, "Estou com uma coisa martelando a minha mente, me perguntando se me livrei de uma cilada ou se perdi o amor da minha vida"),
            FraseEntity(++idContador, celebId, "Eu te vejo em volta em todos estes rostos vazios"),
            FraseEntity(++idContador, celebId, "Mas eu sigo em frente, não posso parar. Não vou parar de me mexer"),
            FraseEntity(++idContador, celebId, "Diga que irá me ver de novo, mesmo que seja em seus sonhos mais loucos"),
            FraseEntity(++idContador, celebId, "Um dia, quando você me deixar, aposto que as lembranças te seguirão."),
            FraseEntity(++idContador, celebId, "Eu adoro os jogadores e você ama o jogo"),
            FraseEntity(++idContador, celebId, "A vida é apenas uma sala de aula."),
            FraseEntity(++idContador, celebId, "Amá-lo é como dirigir um Maserati novo numa rua sem saída."),
            FraseEntity(++idContador, celebId, "Aqui estou eu engolindo o meu orgulho, parada na sua frente dizendo que sinto muito por aquela noite."),
            FraseEntity(++idContador, celebId, "As pessoas querem te ver cair e é sua responsabilidade não as deixar te afetar. Você tem que continuar firme e provar que você está se divertindo muito mais do que eles."),
            FraseEntity(++idContador, celebId, "Cada escolha que eu faço é determinada pelo que eu acho que vão gostar."),
            FraseEntity(++idContador, celebId, "Como você pode não saber? Você pertence a mim."),
            FraseEntity(++idContador, celebId, "Definitivamente não sinto medo em escrever canções sobre minha vida pessoal. Na verdade, isso faz eu sentir como se fosse a única maneira de processar emoções."),
            FraseEntity(++idContador, celebId, "É interessante porque todos os dias da minha vida são documentados de alguma forma, ou há paparazzi do lado de fora do meu apartamento ou fãs me veem em um restaurante e eles tuitam sobre isso."),
            FraseEntity(++idContador, celebId, "É muito difícil saber que tantas pessoas têm uma impressão errada e você não pode chegar nelas e falar: ‘Ei, eu juro que não sou assim’."),
            FraseEntity(++idContador, celebId, "Esquecê-lo foi como tentar conhecer alguém que eu nunca conheci.")
        )
    }
}