package com.joaaoferreiira.celebridades.util

import com.joaaoferreiira.celebridades.database.entity.FraseEntity

object FrasesUtil {

    fun getFrases(): List<FraseEntity> {
        var idContador = 0
        var celebId = 0

        return listOf(
            //Justin Bieber
            FraseEntity(++idContador, ++celebId, "Minha mensagem é que você pode fazer qualquer coisa se você colocar isso na cabeça. Eu cresci abaixo da linha da pobreza, eu não tive tanto quanto as outras pessoas. Acho que isso me fez mais forte como uma pessoa, foi o que construiu meu caráter. Agora eu estou em um grau de 4.0, e quero ir para a faculdade e me tornar uma pessoa melhor."),
            FraseEntity(++idContador, celebId, "Nunca pensei que seria fácil porque ambos estamos tão distantes agora, as paredes estão se fechando sobre nós e estamos nos perguntando como ninguém tem uma resposta concreta. Mas estamos apenas andando no escuro, e você pode ver a expressão no meu rosto, simplesmente me detona"),
            FraseEntity(++idContador, celebId, "Então depende de você e também depende de mim, mas nos encontraremos no meio, no nosso caminho de volta com os pés no chão."),
            FraseEntity(++idContador, celebId, "Eu esperaria por você para sempre, todos os dias. Seu mundo é meu mundo, yeah."),
            FraseEntity(++idContador, celebId, "Nunca diga nunca!"),
            FraseEntity(++idContador, celebId, "Eu nasci para ser alguém,eu vou iluminar o céu, eu nasci para dignificar, eu posso sentir isso, eu posso acreditar,estou aqui para ficar. Sinta, Acredite, Sonhe, Seja!!!"),
            FraseEntity(++idContador, celebId, "Agora Romeu e Julieta nunca se sentiriam do jeito que nos sentimos."),
            FraseEntity(++idContador, celebId, "Não peço que comecem a gostar de mim, eu só peço um pouco de respeito, que nada foi fácil até agora."),
            FraseEntity(++idContador, celebId, "Bem-aventurados todos nós devemos ser capazes de desempenhar um pequeno papel em trazer alegria para a vida das pessoas."),
            FraseEntity(++idContador, celebId, "Eu quero ter meus fãs crescendo comigo e não apenas ser um artista teen. Quero ser um artista quando adulto. Justin Timberlake e Usher, por exemplo. Os dois começaram bem novos e olha como eles fazem as coisas agora."),
            FraseEntity(++idContador, celebId, "Quando eu penso sobre os meus fãs, eu imagino como a Beyoncé faria."),
            FraseEntity(++idContador, celebId, "Ainda gosto de vocês, mas convenhamos: estou com cara de louco. Porém, se você não ri de você mesmo é porque não está se divertindo."),
            FraseEntity(++idContador, celebId, "É muito louco eu, que vim de uma pequena cidade do Canadá, agora poder viajar o mundo todo e fazer o que amo. Eu postava vídeos na internet só para me divertir. Nunca pensei que isso seria possível, então nunca havia sonhado realmente com tudo isso."),
            FraseEntity(++idContador, celebId, "As pessoas escrevem pra mim dizendo: 'Eu estou desistindo, você não está falando comigo.' e eu escrevo (no twitter) uma simples mensagem tipo: 'Nunca desista!' e, isso acaba mudando a vida delas."),
            FraseEntity(++idContador, celebId, "Me sinto o Kurt Cobain da minha geração, mas as pessoas não me compreendem."),
            FraseEntity(++idContador, celebId, "A canção mais pessoal que eu escrevi foi 'Down To Earth', porque é sobre como os meus pais se separaram quando eu era muito novo. Fala da vida cotidiana e de como há regras."),
            FraseEntity(++idContador, celebId, "Eu perco meu apetite sabendo que crianças passam fome à noite. Eu sou um pecador por que meu jantar ainda está no meu prato?"),
            FraseEntity(++idContador, celebId, "Eu nunca vou dizer nunca. Eu lutarei!"),
            FraseEntity(++idContador, celebId, "Eu nunca pensei que poderia sentir esse poder. Eu nunca pensei que pudesse sentir essa liberdade. Eu sou forte o suficiente para subir a torre mais alta e eu sou rápido o suficiente para correr sobre o mar."),
            FraseEntity(++idContador, celebId, "Eu vou lutar para sempre, fazer o certo. Sempre que você me derrubar eu não vou ficar no chão, vou levantar!"),

            //Beyonce
            FraseEntity(++idContador, ++celebId, "Eu te queria tanto, mas não sinto mais isso. Porque, honestamente, você acabou por ser a melhor coisa que nunca tive"),
            FraseEntity(++idContador, celebId, "Eu sempre vou ser sempre a melhor coisa que você nunca teve"),
            FraseEntity(++idContador, celebId, "Você não merece as minhas lágrimas"),
            FraseEntity(++idContador, celebId, "Graças a Deus encontrei o lado bom em dizer adeus"),
            FraseEntity(++idContador, celebId, "Você acorda, perfeita. Bota a cara no sol, perfeita. Anda por aí, perfeita. Se exibe, perfeita"),
            FraseEntity(++idContador, celebId, "Acordei assim! Somos perfeitas, garotas, contem a eles"),
            FraseEntity(++idContador, celebId, "Eu sou perfeita"),
            FraseEntity(++idContador, celebId, "Eu posso sentir o Sol sempre que você está perto. Toda vez que você me toca eu me derreto toda"),
            FraseEntity(++idContador, celebId, "Amor, é você! Você é aquele que eu amo! Você é aquele que eu preciso! Você é o único que eu vejo"),
            FraseEntity(++idContador, celebId, "Você é aquele que dá tudo de si, você é aquele que eu posso sempre chamar. Quando preciso de você, você faz tudo parar"),
            FraseEntity(++idContador, celebId, "Seus lábios tem gosto de uma noite de champanhe"),
            FraseEntity(++idContador, celebId, "Eu arranjo outro como você amanhã. Então não ouse pensar por um segundo sequer que você é insubstituível"),
            FraseEntity(++idContador, celebId, "Está falando sobre como eu nunca vou encontrar um homem igual a você. Você me confundiu com outra pessoa"),
            FraseEntity(++idContador, celebId, "Então, já que eu não sou o seu tudo, que tal eu ser o seu nada?"),
            FraseEntity(++idContador, celebId, "Querido, eu não vou derramar uma lágrima por você, não vou perder uma noite de sono. Porque a mais pura verdade é que substituir você é muito fácil"),
            FraseEntity(++idContador, celebId, "Porque eu sei que não entendo como o seu amor consegue fazer o que ninguém mais consegue"),
            FraseEntity(++idContador, celebId, "Seu amor está me fazendo parecer tão louca agora"),
            FraseEntity(++idContador, celebId, "Em todos os lugares que estou olhando agora eu estou cercada pelo o seu abraço"),
            FraseEntity(++idContador, celebId, "Você é tudo que eu preciso e mais"),
            FraseEntity(++idContador, celebId, "Você é o único que eu quero. Acho que estou viciada na sua luz"),

            //Daniel Radcliffe
            FraseEntity(++idContador, ++celebId, "A vítima de bullying não tem como escapar porque agora o acesso a eles ficou mais fácil. Quando você sofria agressão na escola dava pra fugir no final da aula, mas agora você pode ser caçado por celular, Facebook, Twitter. é assustador"),
            FraseEntity(++idContador, celebId, "Ficarei triste em encerrar a série, mas terei uma grande sensação de dever cumprido quando o filme acabar, porque terá sido a mais longa filmagem que eu provavelmente farei em toda minha carreira"),
            FraseEntity(++idContador, celebId, "Sim, quer dizer, eu coloco numa cesta e ela, de repente, volta limpa. Minhas tarefas em casa são manter meu quarto minimamente arrumado e limpo, num nível aceitável de higiene."),
            FraseEntity(++idContador, celebId, "Os homossexuais devem ter igualdade de direito em todos os lugares. Se você crescer como um jovem gay, sabendo que não tem as mesmas oportunidades que todo mundo, você se sente vítima e prejudica a si mesmo"),
            FraseEntity(++idContador, celebId, "Muitas vezes as pessoas gritam 'Hey Frodo!', porque pensam que sou Elijah (Wood). Eu encaro isso como um elogio, já que ele é um cara muito bonito! Eu admito que quando alguém se confunde e vem me pedir autógrafo, eu dou e assino: 'Com amor, Elijah Wood'. Seria muito triste para mim se eu falasse a verdade e a pessoa desistisse da assinatura“\n"),
            FraseEntity(++idContador, celebId, "O ruim de ficar com uma delas é que você acaba encontrando e tendo que conversar depois. Já aconteceu, mas, tirando algumas vezes, eu estava bêbado“\n"),
            FraseEntity(++idContador, celebId, "Este ano, eu tenho parado para admirar o talento de Ryan Gosling. Acho ele fantástico e parece ser muito legal. Ele parece inteligente. Se eu fosse gay, eu escolheria um homem inteligente como ele"),
            FraseEntity(++idContador, celebId, "Fiquei dependente (da bebida) para desfrutar das coisas. Houve alguns anos nos quais estava apaixonado pela ideia de viver uma vida de pessoa famosa."),
            FraseEntity(++idContador, celebId, "Aquilo (Harry Potter) foi a minha infância, a qual eu disse adeus."),
            FraseEntity(++idContador, celebId, "Estou muito bonito lá de qualquer maneira cara! Tem uma quantidade enorme … Não faço muita manutenção por lá, cara. Quero dizer, só um pouquinho, por cortesia"),
            FraseEntity(++idContador, celebId, "Eu não gosto de garotas com nada lá em baixo também … Esse tipo de mulher me assusta. Você tem que ter alguma coisa, caso contrário, é assustador"),
            FraseEntity(++idContador, celebId, "Eu não acho que o Oscar goste de filmes comerciais, ou filmes de crianças, a menos que sejam dirigidos pelo Martin Scorsese"),
            FraseEntity(++idContador, celebId, "Eu conheço o trabalho de Lady Gaga. Eu a acho brilhante. Ela tem uma linda voz"),
            FraseEntity(++idContador, celebId, "Muito, muito emocionante. Me lembro de ter chorado feito criança"),
            FraseEntity(++idContador, celebId, "Só fui ouvir Justin Bieber pela primeira vez há duas semanas. Ao ouvir a música, pensei que se tratava de uma menina. Nunca o tinha ouvido"),
            FraseEntity(++idContador, celebId, "Tenho muito orgulho de ser judeu. Isso significa que tenho uma boa ética de trabalho, e você tem humor judaico e pode contar piadas judaicas."),
            FraseEntity(++idContador, celebId, "Certa vez, um amigo me chamou (Harry) por acidente. Se houver outra pessoa na sala chamada Harry e alguém gritar seu nome, eu respondo um pouco, o que é embaraçoso. Mas ninguém nunca disse isso nas jogadas da paixão. Esse seria o fim dessa sessão. Vá agora!"),
            FraseEntity(++idContador, celebId, "É bom voltar a filmar. Coloquei meus óculos e me tornei Harry novamente."),
            FraseEntity(++idContador, celebId, "Eu e Harry (Potter) não somos muito bons com mulheres. Eu melhorei agora. Mas acho que qualquer homem que diz que nunca teve um momento estranho com uma garota é mentiroso. Ele é um mentiroso ou é ilusório."),
            FraseEntity(++idContador, celebId, "Eu gostaria de ser ator, mas há muitas outras coisas que também me interessam, como música, escrita e esportes. Eu quero manter minhas opções em aberto."),

            //Wesley Safadao
            FraseEntity(++idContador, ++celebId, "Amor só de mãe, paixão só de cristo, quem quiser me amar...que sofra."),
            FraseEntity(++idContador, celebId, "Faz o que quer e o que não quer de mim."),
            FraseEntity(++idContador, celebId, "Vida de casado é boa, só perde pra de solteiro!"),
            FraseEntity(++idContador, celebId, "Quer me fazer ciúmes de graça. É, eu não sou de retrucar, mas eu vou descontar naquilo que você mais gosta."),
            FraseEntity(++idContador, celebId, "Que eu te amo muita gente sabe, já dei prova em forma de buquê."),
            FraseEntity(++idContador, celebId, "Quem ama também cansa de correr atrás."),
            FraseEntity(++idContador, celebId, "Sonhei que tava me casando e acordei no desespero!"),
            FraseEntity(++idContador, celebId, "Chorar não paga imposto e nem faz mal pra saúde."),
            FraseEntity(++idContador, celebId, "Eu quero e preciso de uma chance, só pra dizer que te amo!"),
            FraseEntity(++idContador, celebId, "Meu coração não pertence a você!"),
            FraseEntity(++idContador, celebId, "Eu não tô dizendo tchau, tô dizendo adeus."),
            FraseEntity(++idContador, celebId, "Realmente se me quiser, vê se muda de atitude."),
            FraseEntity(++idContador, celebId, "Mas se o seu telefone tocar, lá pras três ou quatro da manhã, eu não voltei atrás, eu já bebi demais."),
            FraseEntity(++idContador, celebId, "Você não me cobra e eu não cobro você."),
            FraseEntity(++idContador, celebId, "A gente não precisa de hora marcada, o nosso tempo quem faz é a gente."),
            FraseEntity(++idContador, celebId, "Para mim, a gente não tem solução, eu não vou dar ouvidos ao meu coração."),
            FraseEntity(++idContador, celebId, "Tá sofrendo porquê quer, podia tá comigo e tá sozinha."),
            FraseEntity(++idContador, celebId, "Eu sei que beija o meu rosto, mas quer minha boca."),
            FraseEntity(++idContador, celebId, "Quero ver até onde você vai, tá me soltando demais, olha que eu posso sumir."),
            FraseEntity(++idContador, celebId, "O seu tempo tá se acabando e eu já me cansei, só que você não vê."),

            //Whindersson
            FraseEntity(++idContador, ++celebId, "Namoro à distância não é problema nenhum, porque é como diz aquele provérbio chinês: mais vale um amor na mão, do que dois voando. Deus ajuda quem cedo madruga pra comprar passagem e ver a pessoa."),
            FraseEntity(++idContador, celebId, "Não é fácil a vida."),
            FraseEntity(++idContador, celebId, "O dente do rico, quando ele vai nascer, ele permissão ao dente de leite."),
            FraseEntity(++idContador, celebId, "O homem só conversa de problema com outro homem se ele quiser resolver o problema. Quando a mulher fala de um problema com um homem, é porque ela quer dialogar, conversar."),
            FraseEntity(++idContador, celebId, "O meu maior medo na escola era a escola."),
            FraseEntity(++idContador, celebId, "O mundo todo tá uma merda, o mundo inteiro é uma merda, as pessoas que estão no mundo, elas são o extrato da merda."),
            FraseEntity(++idContador, celebId, "O pessoal da escola me chamava de ‘cabeça de pica’."),
            FraseEntity(++idContador, celebId, "O pobre não sabe agir em conjunto. Eles começam a fazer as coisas e não dá nem cinco minutos e já estão brigando."),
            FraseEntity(++idContador, celebId, "O pobre passa a virada do ano aonde: em casa, no mesmo lugar que foi a ceia de Natal, a árvore de Natal ainda está lá, os pisca-pisca tá tudo lá, e vai ficar lá até o carnaval."),
            FraseEntity(++idContador, celebId, "O Tony Ramos de cinco em cinco segundos ele está com um cortador de grama, senão a mulher dele vai procurar e não acha mais ele nos cabelos."),
            FraseEntity(++idContador, celebId, "Parece que rola tem vida própria. Do nada ela acorda e quer ver o que está acontecendo."),
            FraseEntity(++idContador, celebId, "Pesquisa, estuda, vá pra cima."),
            FraseEntity(++idContador, celebId, "Quando a pessoa termina o namoro, ás vezes ela quer esquecer que ela terminou o namoro, mas as pessoas que estão ao redor dela fazem questão de lembrar."),
            FraseEntity(++idContador, celebId, "Se beber, não tweete."),
            FraseEntity(++idContador, celebId, "Se o mundo precisasse de mim pra evoluir, ele tava a mesma merda jurássica ainda."),
            FraseEntity(++idContador, celebId, "Se tem uma coisa que freia o homem, é mulher."),
            FraseEntity(++idContador, celebId, "Se tu continuar falando ‘crush’, tu não vai arrumar nem um jumento pra tu."),
            FraseEntity(++idContador, celebId, "Todo ovo coça. Ás vezes, eu vejo um ovo da páscoa e eu quero coçar."),
            FraseEntity(++idContador, celebId, "Doido só dá certo com doido."),
            FraseEntity(++idContador, celebId, "Celular e bebida não combinam. Principalmente pra quem tem Twitter."),

            //Ayrton Senna
            FraseEntity(++idContador, ++celebId, "O medo faz parte da vida da gente. Algumas pessoas não sabem como enfrentá-lo, outras - acho que estou entre elas - aprendem a conviver com ele e o encaram não como uma coisa negativa, mas como um sentimento de autopreservação."),
            FraseEntity(++idContador, celebId, "No que diz respeito ao empenho, ao compromisso, ao esforço, à dedicação, não existe meio termo. Ou você faz uma coisa bem feita ou não faz."),
            FraseEntity(++idContador, celebId, "Dinheiro é um negócio curioso. Quem não tem está louco para ter; quem tem está cheio de problemas por causa dele."),
            FraseEntity(++idContador, celebId, "O dia que chegar, chegou. Pode ser hoje ou daqui a 50 anos. A única coisa certa é que ela vai chegar."),
            FraseEntity(++idContador, celebId, "Vencer é o que importa. O resto é a consequência."),
            FraseEntity(++idContador, celebId, "Eu sou feliz. Serei plenamente feliz, talvez, se chegar com sabedoria aos 60 anos. De qualquer forma, ainda tenho muita vida pela frente."),
            FraseEntity(++idContador, celebId, "O medo me fascina."),
            FraseEntity(++idContador, celebId, "Mulheres - com elas uma encrenca, mas sem elas não se pode viver."),
            FraseEntity(++idContador, celebId, "Não sei dirigir de outra maneira que não seja arriscada. Quando tiver de ultrapassar vou ultrapassar mesmo. Cada piloto tem o seu limite. O meu é um pouco acima do dos outros."),
            FraseEntity(++idContador, celebId, "Meu maior erro? Acho que ainda está para acontecer."),
            FraseEntity(++idContador, celebId, "Acidentes são inesperados e indesejados, mas fazem parte da vida. No momento em que você se senta num carro de corrida e está competindo para vencer, o segundo ou o terceiro lugar não satisfazem. Ou você se compromete com o objetivo da vitória ou não. Isso que dizer: ou você corre ou não."),
            FraseEntity(++idContador, celebId, "Vocês nunca conseguirão saber como um piloto se sente quando vence uma prova. O capacete oculta sentimentos incompreensíveis."),
            FraseEntity(++idContador, celebId, "Para ser honesto, não me sinto o maior ídolo brasileiro. Não me sinto uma pessoa tão importante assim para merecer uma festa durante uma noite toda no Brasil."),
            FraseEntity(++idContador, celebId, "Nunca precisei mostrar que em determinado GP eu estava com uma loira de olhos azuis ou em outro GP com uma morenaça. Quando aconteceu, foi uma coisa natural e nunca para mostrar aos outros que eu sou garanhão e tenho dezenas de mulheres. Se eu tive uma dezena de mulheres, foi para mim mesmo."),
            FraseEntity(++idContador, celebId, "Seja você quem for, seja qual for a posição social que você tenha na vida, a mais alta ou a mais baixa, tenha sempre como meta muita força, muita determinação e sempre faça tudo com muito amor e com muita fé em Deus, que um dia você chega lá. De alguma maneira você chega lá."),
            FraseEntity(++idContador, celebId, "Se você quer ser bem sucedido, precisa ter dedicação total, buscar seu último limite e dar o melhor de si."),
            FraseEntity(++idContador, celebId, "Deus é Grande Deus e forte, quando ele quer não tem quem não queira."),
            FraseEntity(++idContador, celebId, "Uma maneira de preservar sua própria imagem é não deixar que o mundo invada sua casa. Foi um modo que encontrei de preservar ao máximo meus valores."),
            FraseEntity(++idContador, celebId, "O segundo nada mais é do que o primeiro dos perdedores."),
            FraseEntity(++idContador, celebId, "Eu não tenho ídolos. Tenho admiração por trabalho, dedicação e competência."),

            //David Googis
            FraseEntity(++idContador, ++celebId, "Você tem que criar calos no seu cérebro, assim como você cria calos nas suas mãos. Calejando sua mente através da dor e sofrimento."),
            FraseEntity(++idContador, celebId, "Para ser a pessoa que eu queria me tornar, eu me via como a pessoa mais fraca (que Deus) já criou. Eu queria mudar isso para ser o homem mais difícil já criado."),
            FraseEntity(++idContador, celebId, "A única pessoa que iria mudar minha vida era eu. A única maneira de me virar era me colocar nas piores coisas possíveis que um ser humano poderia suportar."),
            FraseEntity(++idContador, celebId, "Como seres humanos, estamos lendo livros todos os dias para tentar descobrir como ser outra pessoa. O que não fazemos é entrar, virar-se do avesso e ler nossa própria história. Você tem que olhar para dentro para descobrir o que realmente deseja."),
            FraseEntity(++idContador, celebId, "Usamos essas palavras e frases que \"Somente os fortes sobrevivem\" e todas essas outras porcarias. São apenas palavras (palavrões)."),
            FraseEntity(++idContador, celebId, "A única maneira de você chegar ao outro lado dessa jornada é sofrendo. Você tem que sofrer para crescer. Algumas pessoas entendem, outras não."),
            FraseEntity(++idContador, celebId, "Conversa interna e visualização são as duas chaves do meu sucesso. ”"),
            FraseEntity(++idContador, celebId, "A grandeza puxa a mediocridade para a lama. Vá lá fora e vá atrás"),
            FraseEntity(++idContador, celebId, "Quando você olha no espelho, essa é a única pessoa para quem você não pode mentir."),
            FraseEntity(++idContador, celebId, "\"Fui guiado por algo muito mais poderoso: o caminho da maior resistência. Talento, não é obrigatório."),
            FraseEntity(++idContador, celebId, "A vida é um grande cabo de guerra entre a mediocridade e a tentativa de encontrar o seu melhor."),
            FraseEntity(++idContador, celebId, "Ninguém se importa com o que você fez ontem. O que você fez hoje para melhorar a si mesmo?"),
            FraseEntity(++idContador, celebId, "Todo mundo quer uma solução rápida. Você pode obter resultados, mas eles não serão permanentes. Os resultados permanentes vêm de você ter que sofrer."),
            FraseEntity(++idContador, celebId, "\"Estou falando de calejar a mente. Faça algo que seja péssimo."),
            FraseEntity(++idContador, celebId, "Motivação é uma porcaria. Motivação vem e vai. Quando você é conduzido, o que estiver à sua frente será destruído."),
            FraseEntity(++idContador, celebId, "Tem um monte de caras que não gostam de mim e eu não dou a mínima (palavrão). Sou um guerreiro."),
            FraseEntity(++idContador, celebId, "A pior coisa que pode acontecer a um homem é tornar-se civilizado"),
            FraseEntity(++idContador, celebId, "Você falhará, estará na sua cabeça e dirá que não sou bom o suficiente. É sobre como você supera isso."),
            FraseEntity(++idContador, celebId, "Todo mundo quer uma solução rápida, como abdominais de 6 minutos - você pode obter alguns resultados, mas esses resultados não serão permanentes. Os resultados permanentes vêm de você ter que sofrer. Você precisa fazer uma tatuagem no seu cérebro para que, quando a dificuldade voltar, você não a esqueça."),
            FraseEntity(++idContador, celebId, "Teoria é besteira. Quando você se coloca no inferno, essa é a única maneira de perceber como superar isso. Você não pode ler o livro de outra pessoa sobre alguma teoria sobre como fazer (palavrão). Um cara que estava sentado em seu escritório quente e escreveu um livro com uma boa xícara de café na mão. NÃO - Quero aprender com aquele cara que mergulhou no inferno que pensou em desistir e sair: 'Por que estou aqui?', 'Isso vale a pena?' E ainda descobri uma maneira de superar isso."),

            //Mestre Yoda
            FraseEntity(++idContador, ++celebId, "O medo é o caminho para o lado negro."),
            FraseEntity(++idContador, celebId, "Treine a si mesmo a deixar partir tudo que teme perder."),
            FraseEntity(++idContador, celebId, "Faça ou não faça. A tentativa não existe."),
            FraseEntity(++idContador, celebId, "Difícil de ver. Sempre em movimento está o Futuro."),
            FraseEntity(++idContador, celebId, "Muitas das verdades que temos dependem de nosso ponto de vista."),
            FraseEntity(++idContador, celebId, "Que a Força esteja com você!"),
            FraseEntity(++idContador, celebId, "Treinar para libertar-se de tudo que tens medo a perder é necessário."),
            FraseEntity(++idContador, celebId, "O medo leva à raiva, a raiva leva ao ódio e o ódio leva ao sofrimento."),
            FraseEntity(++idContador, celebId, "Grande guerreiro? Guerra não faz grande ninguém."),
            FraseEntity(++idContador, celebId, "O seu foco é a sua realidade."),
            FraseEntity(++idContador, celebId, "Ensine sempre o que você aprendeu."),
            FraseEntity(++idContador, celebId, "Um Jedi usa a Força para sabedoria e defesa, nunca para o ataque."),
            FraseEntity(++idContador, celebId, "Tamanho importa não. Olhe para mim, você me julga pelo tamanho?"),
            FraseEntity(++idContador, celebId, "Em um estado sombrio nós nos encontramos... um pouco mais de conhecimento iluminar nosso caminho pode."),
            FraseEntity(++idContador, celebId, "O lado negro não é mais poderoso, apenas mais rápido, mais fácil e mais sedutor."),
            FraseEntity(++idContador, celebId, "A morte é parte natural da Vida. Regozije-se por aqueles que se uniram com a Força. Não lamente por eles. Não sinta falta deles. O apego leva à inveja. À sombra da cobiça, isso sim."),
            FraseEntity(++idContador, celebId, "Melhor professor, o fracasso é."),
            FraseEntity(++idContador, celebId, "Só é diferente na sua mente. Você precisa desaprender o que aprendeu."),
            FraseEntity(++idContador, celebId, "Muito a aprender você ainda tem."),
            FraseEntity(++idContador, celebId, "O medo da perda é um caminho para o lado negro."),

            //Luan Santana
            FraseEntity(++idContador, ++celebId, "Já me ganhou, agora é só me levar pra você"),
            FraseEntity(++idContador, celebId, "Mas aconteceu foi mais forte que eu e você"),
            FraseEntity(++idContador, celebId, "Era pra ser agora quando é pra acontecer. Tem dia, lugar e tem hora"),
            FraseEntity(++idContador, celebId, "A sua boca vale o preço, pra perder o sossego que eu tinha"),
            FraseEntity(++idContador, celebId, "Os quatro perdidos de amor Eu, você, o mar e ela"),
            FraseEntity(++idContador, celebId, "Tô no teu reflexo no espelho, no teu travesseiro, sonho e pesadelo "),
            FraseEntity(++idContador, celebId, "E quando acordar, eu tô aí, mesmo sem estar"),
            FraseEntity(++idContador, celebId, "Quando tento escapar, chego ainda mais perto"),
            FraseEntity(++idContador, celebId, "Aceito esse amor unilateral… "),
            FraseEntity(++idContador, celebId, "Não há razões para não ser feliz, mas pra ser feliz , preciso de uma razão"),
            FraseEntity(++idContador, celebId, "Vamo acordar esse prédio, fazer inveja pro povo…"),
            FraseEntity(++idContador, celebId, "Sempre foi você o fantasma do meu "),
            FraseEntity(++idContador, celebId, "Se beber, hoje fosse minha única opção pra por um curativo no meu"),
            FraseEntity(++idContador, celebId, "Até te esqueceria por cinco minutos, mas não pra sempre "),
            FraseEntity(++idContador, celebId, "Até bateu saudade do seu mau humor…"),
            FraseEntity(++idContador, celebId, "Mas foi só te ver, caiu a ficha do quanto eu te quero "),
            FraseEntity(++idContador, celebId, "Olha eu de novo, na estaca zero…"),
            FraseEntity(++idContador, celebId, "Não existe nada mais que me fascina, Que te ver chegar  "),
            FraseEntity(++idContador, celebId, "Não mudei de cidade, nem de telefone Só escolhi ser feliz"),
            FraseEntity(++idContador, celebId, "Muito mais que um dia eu sonhei pra mim "),

            //PewDiePie
            FraseEntity(++idContador, ++celebId, "Não seja uma salada. Seja o melhor maldito brócolis que você pode ser"),
            FraseEntity(++idContador, celebId, "A menos que você pare de tentar, como você não pode mais falhar."),
            FraseEntity(++idContador, celebId, "Era muito mais fácil me conectar com meus fãs quando eu era menor. Eu poderia responder todas as mensagens e gostar disso."),
            FraseEntity(++idContador, celebId, "A vida é muito curta para se concentrar nas coisas que você odeia, se concentrar no que você ama"),
            FraseEntity(++idContador, celebId, "Comentários são a minha principal maneira de me comunicar com seus irmãos."),
            FraseEntity(++idContador, celebId, "Com o meu canal e com o que as pessoas associam à Internet, a maioria das pessoas pensa que ela se torna viral, você se torna uma coisa enorme super rápida. Eu nunca tive uma explosão ou uma coisa enorme. É apenas algo que vem crescendo progressivamente. Está construindo."),
            FraseEntity(++idContador, celebId, "O que tornou o YouTube tão bem-sucedido é que você pode se relacionar muito mais com as pessoas que está assistindo do que com as pessoas que vê na TV."),
            FraseEntity(++idContador, celebId, "Eu só quero entreter; esse é o meu principal objetivo e o que vem antes de tudo."),
            FraseEntity(++idContador, celebId, "Hoje em dia, todo mundo já jogou videogame e os videogames são divertidos."),
            FraseEntity(++idContador, celebId, "Gostaria de ajudar outros YouTubers."),
            FraseEntity(++idContador, celebId, "Quando iniciei meu canal do YouTube em 2010, nunca imaginei que um dia seria o canal mais inscrito no mundo e que faria parte de uma comunidade tão boa."),
            FraseEntity(++idContador, celebId, "O que eu e outros YouTubers fazemos é uma coisa muito diferente; é quase como passear e assistir seu amigo jogar .."),
            FraseEntity(++idContador, celebId, "Todos têm direito a suas opiniões, mesmo que estejam errados."),
            FraseEntity(++idContador, celebId, "Nada é mais fácil se você é um idiota."),
            FraseEntity(++idContador, celebId, "A cada segundo você está mais perto do esquecimento. Nenhuma citação no mundo vai mudar isso."),
            FraseEntity(++idContador, celebId, "Seja legal com as pessoas; talvez um dia eles sejam ricos."),
            FraseEntity(++idContador, celebId, "Faça coisas estúpidas agora porque, quando você for mais velho, terá problemas."),
            FraseEntity(++idContador, celebId, "Eu amo este jogo. É tão incrível."),
            FraseEntity(++idContador, celebId, "Quando comecei, eu não podia nem comprar um computador adequado para gravar a jogabilidade."),
            FraseEntity(++idContador, celebId, "Eu amo fazer esses vídeos."),

            //Felipe Neto
            FraseEntity(++idContador, ++celebId, "Julgamo-nos tão espertos, tão analíticos, tão maduros e, no final das contas, somos todos formados por medos, inseguranças e sonhos. Criticamos e condenamos aquilo que não somos, mas que nos incomoda e, se por fato tomamos a premissa, não podemos dizer que somos indiferentes. Já dizia Dona Maria: “nenhum dos pregos misturados na caixinha toma martelada, apenas o que sai dela”. Virar alvo de críticas me ensinou, principalmente, que mesmo na pior das análises não há a indiferença. Isso, por si só, é razão para sorrir."),
            FraseEntity(++idContador, celebId, "Um vampiro se apaixonar por um ser humano é a mesma coisa que você se apaixonar por uma vaca."),
            FraseEntity(++idContador, celebId, "Não me odeiem... Ou me odeiem, dane-se!"),
            FraseEntity(++idContador, celebId, "A vida na casa da minha mãe já estava insuportavelmente chata."),
            FraseEntity(++idContador, celebId, "Chamei minha mãe e meu tio para um passeio, pegamos o carro, entramos no Buraco do Padre e tomamos o caminho do shopping."),
            FraseEntity(++idContador, celebId, "O importante é que uma ideia jamais deve ser adiada."),
            FraseEntity(++idContador, celebId, "Eu adoro pasta de amendoim. Se alguém quiser me dar um presente, um dia, é só ir numa importadora e comprar uma daquelas pastas de amendoim americanas, sabe? É uma delícia, você coloca no pão, no biscoito e até faz doce."),
            FraseEntity(++idContador, celebId, "Amigos, morar sozinho pela primeira vez não é fácil. É assustador descobrir que sua roupa não sai milagrosamente do cesto de roupa suja e aparece limpinha, passada e dobrada na sua gaveta."),
            FraseEntity(++idContador, celebId, "Lavar cuecas no banho é uma tarefa que nenhum homem consegue suportar por muito tempo. Não foi à toa que chegou um momento em que eu precisava escolher a cueca de acordo com a que estava menos suja, através do teste da fungada. Nojento?"),
            FraseEntity(++idContador, celebId, "A única diferença entre uma pessoa que conquistou seus sonhos e uma pessoa que não realizou é que uma conquistou e a outra não. Pense nisso."),
            FraseEntity(++idContador, celebId, "Minha Vida Não Faz Sentido."),
            FraseEntity(++idContador, celebId, "Tudo que aconteceu poderia ter acontecido de outra forma."),
            FraseEntity(++idContador, celebId, "Aprenda que até os bons, aprendem com a maldade!"),
            FraseEntity(++idContador, celebId, "Toda coragem necessariamente precisa de um medo para existir! Tenha coragem!"),
            FraseEntity(++idContador, celebId, "E quando alguém te ignorar no Whatsapp, simplesmente não ligue, lembre-se: você já era ignorado antes, apenas não sabia disso."),
            FraseEntity(++idContador, celebId, "Afinal, amor é amor... Não se esconda em arrependimento, apenas ame-se e você estará no caminho certo."),
            FraseEntity(++idContador, celebId, "O segredo da vida é você justamente juntar toda a sua coragem e fazer aquilo que achou que teria medo demais para fazer."),
            FraseEntity(++idContador, celebId, "Se a Terra não girasse, existiriam menos tontos no mundo?"),
            FraseEntity(++idContador, celebId, "Existem momentos em que se deve fazer a paz. Momentos em que se deve fazer amor. E, principalmente, momentos em que se deve fazer café."),
            FraseEntity(++idContador, celebId, "Beleza é uma questão de fé. Eu acredito que sou bonito, o difícil é convencer os outros."),

            //Alan Turing
            FraseEntity(++idContador, ++celebId, "O corpo fornece alguma coisa para o espírito cuidar e usar."),
            FraseEntity(++idContador, celebId, "Essas perguntas substituem a nossa original, \"Podem as máquinas pensar?"),
            FraseEntity(++idContador, celebId, "Receio que o seguinte silogismo possa ser usado por alguns no futuro. Turing acredita que as máquinas pensam Turing encontra-se com os homens Portanto, as máquinas não pensam no seu sofrimento"),
            FraseEntity(++idContador, celebId, "Às vezes, são as pessoas que ninguém pode imaginar nada de quem faz as coisas que ninguém pode imaginar."),
            FraseEntity(++idContador, celebId, "Se se espera que uma máquina seja infalível, ela também não pode ser inteligente."),
            FraseEntity(++idContador, celebId, "O raciocínio matemático pode ser considerado esquematicamente como o exercício de uma combinação de duas facilidades, que podemos chamar de intuição e engenhosidade."),
            FraseEntity(++idContador, celebId, "Acredito que, no final do século, o uso de palavras e opiniões educadas em geral tenha mudado tanto que alguém será capaz de falar de máquinas pensando sem esperar ser contrariado."),
            FraseEntity(++idContador, celebId, "Quem pode imaginar qualquer coisa, pode criar o impossível."),
            FraseEntity(++idContador, celebId, "Podemos ver apenas uma curta distância à frente, mas podemos ver muitas coisas que precisam ser feitas."),
            FraseEntity(++idContador, celebId, "A maioria deles parece ser \"subcrítica\", isto é, corresponder nesta analogia a pilhas de tamanho subcrítico. Uma idéia apresentada a essa mente dará, em média, menos de uma idéia em resposta. Uma proporção pequena é super-crítica. Uma idéia apresentada a essa mente pode dar origem a toda uma \"teoria\" que consiste em idéias secundárias, terciárias e mais remotas."),
            FraseEntity(++idContador, celebId, "Não estou muito impressionado com argumentos teológicos, sejam eles quais forem, para apoiar. Tais argumentos foram freqüentemente considerados insatisfatórios no passado"),
            FraseEntity(++idContador, celebId, "A visão de que as máquinas não podem causar surpresas se deve, creio eu, a uma falácia à qual filósofos e matemáticos estão particularmente sujeitos. Essa é a suposição de que, assim que um fato é apresentado à mente, todas as conseqüências desse fato surgem na mente simultaneamente com ele. É uma suposição muito útil em muitas circunstâncias, mas esquecemos com muita facilidade que ela é falsa"),
            FraseEntity(++idContador, celebId, "A pergunta original, 'As máquinas podem pensar?' Eu acredito que seja sem sentido demais para merecer discussão"),
            FraseEntity(++idContador, celebId, "Máquinas me pegam de surpresa com grande frequência"),
            FraseEntity(++idContador, celebId, "Não queremos penalizar a máquina por sua incapacidade de brilhar em competições de beleza, nem penalizar um homem por perder em uma corrida contra um avião. As condições do nosso jogo tornam essas deficiências irrelevantes."),
            FraseEntity(++idContador, celebId, "As tabelas de instruções deverão ser compostas por matemáticos com experiência em computação e talvez com uma certa capacidade de resolução de quebra-cabeças. Não há nenhum perigo real de que isso se torne uma chatice, pois qualquer processo bastante mecânico pode ser entregue à própria máquina."),
            FraseEntity(++idContador, celebId, "Presumivelmente, o cérebro infantil é algo parecido com um caderno de notas que se compra no papel de carta. Pouco mecanismo e muitas folhas em branco."),
            FraseEntity(++idContador, celebId, "O Princípio da Exclusão é estabelecido exclusivamente para o benefício dos próprios elétrons, que podem ser corrompidos (e se tornarem dragões ou demônios) se forem autorizados a se associar livremente."),
            FraseEntity(++idContador, celebId, "Um homem provido de papel, lápis e borracha, sujeito a uma disciplina estrita, é de fato uma máquina universal."),
            FraseEntity(++idContador, celebId, "As máquinas não podem realizar algo que deva ser descrito como pensamento, mas que é muito diferente do que o homem faz?"),

            //Linux
            FraseEntity(++idContador, ++celebId, "O software é como sexo, é melhor quando é livre."),
            FraseEntity(++idContador, celebId, "Sério, eu não tenho por meta destruir a Microsoft. Este será um efeito colateral completamente involuntário"),
            FraseEntity(++idContador, celebId, "Dijkstra provavelmente me odeia."),
            FraseEntity(++idContador, celebId, "Meu nome é Linus, e eu sou seu deus."),
            FraseEntity(++idContador, celebId, "Falar é fácil. Mostre-me o código."),
            FraseEntity(++idContador, celebId, "Meu nome é Linus Torvalds e eu sou seu deus."),
            FraseEntity(++idContador, celebId, "A Microsoft não é má, apenas cria sistemas operacionais realmente ruins."),
            FraseEntity(++idContador, celebId, "Dados globos oculares suficientes, todos os erros são superficiais."),
            FraseEntity(++idContador, celebId, "Minha opinião pessoal de Mach não é muito alta. Francamente, é um pedaço de merda. Ele contém todos os erros de design que você pode cometer e até conseguiu cometer alguns deles."),
            FraseEntity(++idContador, celebId, "Algumas pessoas me disseram que não acham que um pinguim gordo realmente incorpore a graça do Linux, o que me diz que nunca viram um pinguim zangado cobrando mais de 160 km / h. Eles teriam muito mais cuidado com o que dizem se tivessem."),
            FraseEntity(++idContador, celebId, "Bem, com um assunto como esse, tenho medo de responder. Desculpas aos usuários do minix que já ouviram o suficiente sobre o Linux. Eu gostaria de ser capaz de \"ignorar a isca\", mas ... tempo para um sério incêndio de chama!"),
            FraseEntity(++idContador, celebId, "Quem vier com \"mantenha pressionada a tecla Shift por oito segundos para ativar o modo 'o teclado está com defeito'\" deve ser filmado."),
            FraseEntity(++idContador, celebId, "Se você já realizou algum trabalho de segurança - e não envolveu o conceito de \"rede de confiança\" - não era trabalho de segurança, era - masturbação. Eu não sei o que você estava fazendo. Mas confie em mim, é a única maneira de fazer segurança, é a única maneira de fazer desenvolvimento."),
            FraseEntity(++idContador, celebId, "Seu trabalho é ser professor e pesquisador: essa é uma ótima desculpa para alguns dos danos cerebrais do Minix."),
            FraseEntity(++idContador, celebId, "Bem, eu provavelmente não vou conseguir notas muito boas, mesmo sem você: eu tive uma discussão (completamente sem relação - nem mesmo referente a sistemas operacionais) com a pessoa aqui na universidade que ensina design de sistemas operacionais. Gostaria de saber quando vou aprender"),
            FraseEntity(++idContador, celebId, "Espero não ter que caçar todos vocês e matá-los enquanto dorme."),
            FraseEntity(++idContador, celebId, "Olha aqui, seu compilador faz algumas coisas absolutamente insanas com o derramamento, incluindo o derramamento de uma * constante *. Pelo amor de Deus, esse compilador não deveria ter permissão para se formar no jardim de infância. Estamos falando de \"preguiça que caiu na cabeça quando bebê\" aqui nos níveis de retardo."),
            FraseEntity(++idContador, celebId, "Chorar por ser um bug do aplicativo é como chorar pela velocidade da luz: você deve lidar com a realidade, não o que deseja que a realidade seja."),
            FraseEntity(++idContador, celebId, "PCs modernos são horríveis. A ACPI é um desastre completo de design em todos os aspectos. Mas estamos meio que presos a isso. Se alguém da Intel estiver ouvindo isso e você tiver algo a ver com a ACPI, tire uma foto agora mesmo, antes de se reproduzir."),

            //14 celebridade
            FraseEntity(++idContador, ++celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),

            //15 celebridade
            FraseEntity(++idContador, ++celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),

            //16 celebridade
            FraseEntity(++idContador, ++celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),

            //17 celebridade
            FraseEntity(++idContador, ++celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),

            //18 celebridade
            FraseEntity(++idContador, ++celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),

            //19 celebridade
            FraseEntity(++idContador, ++celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),

            //20 celebridade
            FraseEntity(++idContador, ++celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, "")
        )
    }
}