package com.joaaoferreiira.celebridades.util

import com.joaaoferreiira.celebridades.database.entity.FraseEntity

object FrasesUtil {

    fun getFrases(): List<FraseEntity> {
        var idContador = 0
        var celebId = 0

        return listOf(
            //Justin Bieber
            FraseEntity(++idContador, ++celebId, "Minha mensagem é que você pode fazer qualquer coisa se você colocar isso na cabeça. Eu cresci abaixo da linha da pobreza, eu não tive tanto quanto as outras pessoas. Acho que isso me fez mais forte como uma pessoa, foi o que construiu meu caráter. Agora eu estou em um grau de 4.0, e quero ir para a faculdade e me tornar uma pessoa melhor."),
            FraseEntity(++idContador, celebId, "Nunca pensei que seria fácil porque ambos estamos tão distantes agora, as paredes estão se fechando sobre nós e estamos nos perguntando como ninguém tem uma resposta concreta. Mas estamos apenas andando no escuro, e você pode ver a expressão no meu rosto, simplesmente me detona"),
            FraseEntity(++idContador, celebId, "Então depende de você e também depende de mim, mas nos encontraremos no meio, no nosso caminho de volta com os pés no chão."),
            FraseEntity(++idContador, celebId, "Eu esperaria por você para sempre, todos os dias. Seu mundo é meu mundo, yeah."),
            FraseEntity(++idContador, celebId, "Nunca diga nunca!"),
            FraseEntity(++idContador, celebId, "Eu nasci para ser alguém,eu vou iluminar o céu, eu nasci para dignificar, eu posso sentir isso, eu posso acreditar,estou aqui para ficar. Sinta, Acredite, Sonhe, Seja!!!"),
            FraseEntity(++idContador, celebId, "Agora Romeu e Julieta nunca se sentiriam do jeito que nos sentimos."),
            FraseEntity(++idContador, celebId, "Não peço que comecem a gostar de mim, eu só peço um pouco de respeito, que nada foi fácil até agora."),
            FraseEntity(++idContador, celebId, "Bem-aventurados todos nós devemos ser capazes de desempenhar um pequeno papel em trazer alegria para a vida das pessoas."),
            FraseEntity(++idContador, celebId, "Eu quero ter meus fãs crescendo comigo e não apenas ser um artista teen. Quero ser um artista quando adulto. Justin Timberlake e Usher, por exemplo. Os dois começaram bem novos e olha como eles fazem as coisas agora."),
            FraseEntity(++idContador, celebId, "Quando eu penso sobre os meus fãs, eu imagino como a Beyoncé faria."),
            FraseEntity(++idContador, celebId, "Ainda gosto de vocês, mas convenhamos: estou com cara de louco. Porém, se você não ri de você mesmo é porque não está se divertindo."),
            FraseEntity(++idContador, celebId, "É muito louco eu, que vim de uma pequena cidade do Canadá, agora poder viajar o mundo todo e fazer o que amo. Eu postava vídeos na internet só para me divertir. Nunca pensei que isso seria possível, então nunca havia sonhado realmente com tudo isso."),
            FraseEntity(++idContador, celebId, "As pessoas escrevem pra mim dizendo: 'Eu estou desistindo, você não está falando comigo.' e eu escrevo (no twitter) uma simples mensagem tipo: 'Nunca desista!' e, isso acaba mudando a vida delas."),
            FraseEntity(++idContador, celebId, "Me sinto o Kurt Cobain da minha geração, mas as pessoas não me compreendem."),
            FraseEntity(++idContador, celebId, "A canção mais pessoal que eu escrevi foi 'Down To Earth', porque é sobre como os meus pais se separaram quando eu era muito novo. Fala da vida cotidiana e de como há regras."),
            FraseEntity(++idContador, celebId, "Eu perco meu apetite sabendo que crianças passam fome à noite. Eu sou um pecador por que meu jantar ainda está no meu prato?"),
            FraseEntity(++idContador, celebId, "Eu nunca vou dizer nunca. Eu lutarei!"),
            FraseEntity(++idContador, celebId, "Eu nunca pensei que poderia sentir esse poder. Eu nunca pensei que pudesse sentir essa liberdade. Eu sou forte o suficiente para subir a torre mais alta e eu sou rápido o suficiente para correr sobre o mar."),
            FraseEntity(++idContador, celebId, "Eu vou lutar para sempre, fazer o certo. Sempre que você me derrubar eu não vou ficar no chão, vou levantar!"),

            //Segunda celebridade
            FraseEntity(++idContador, ++celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),

            //Terceira celebridade
            FraseEntity(++idContador, ++celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),

            //Quarta celebridade
            FraseEntity(++idContador, ++celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),

            //Quinta celebridade
            FraseEntity(++idContador, ++celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),

            //Sexta celebridade
            FraseEntity(++idContador, ++celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),

            //Setima celebridade
            FraseEntity(++idContador, ++celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),

            //Oitava celebridade
            FraseEntity(++idContador, ++celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),

            //Nona celebridade
            FraseEntity(++idContador, ++celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),

            //Decima celebridade
            FraseEntity(++idContador, ++celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, ""),
            FraseEntity(++idContador, celebId, "")
        )
    }
}